source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '15.0'


target 'Rewards_Example' do
  pod 'TikiRewards', :path => '../'
  pod 'CaptureReceipt', :path => '../../capture-receipt-ios'
  pod 'BlinkReceipt', '~> 1.27'
  pod 'BlinkEReceipt', '~> 2.0'
  pod 'TikiSdkDebug', '3.0.0', :configurations => 'Debug'
  pod 'TikiSdkRelease', '3.0.0', :configurations => 'Release'

  target 'Rewards_Tests' do
    inherit! :search_paths
  end
end
