use_frameworks!

platform :ios, '10.0'

target 'Rewards_Example' do
  pod 'Rewards', :path => '../'

  target 'Rewards_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
